abstract class NotificationApiState{}
class NotificationApiInitState extends NotificationApiState{}
class NotificationListApiState extends NotificationApiState{}
class MapNotificationApiState extends NotificationApiState{}